/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionSessionIdRouteImport } from './routes/session.$sessionId'
import { Route as SessionSessionIdDetailsRouteImport } from './routes/session.$sessionId.details'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdDetailsRoute = SessionSessionIdDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => SessionSessionIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/session/$sessionId': typeof SessionSessionIdRouteWithChildren
  '/session/$sessionId/details': typeof SessionSessionIdDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/session/$sessionId': typeof SessionSessionIdRouteWithChildren
  '/session/$sessionId/details': typeof SessionSessionIdDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/session/$sessionId': typeof SessionSessionIdRouteWithChildren
  '/session/$sessionId/details': typeof SessionSessionIdDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/session/$sessionId' | '/session/$sessionId/details'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/session/$sessionId' | '/session/$sessionId/details'
  id: '__root__' | '/' | '/session/$sessionId' | '/session/$sessionId/details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionSessionIdRoute: typeof SessionSessionIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId/details': {
      id: '/session/$sessionId/details'
      path: '/details'
      fullPath: '/session/$sessionId/details'
      preLoaderRoute: typeof SessionSessionIdDetailsRouteImport
      parentRoute: typeof SessionSessionIdRoute
    }
  }
}

interface SessionSessionIdRouteChildren {
  SessionSessionIdDetailsRoute: typeof SessionSessionIdDetailsRoute
}

const SessionSessionIdRouteChildren: SessionSessionIdRouteChildren = {
  SessionSessionIdDetailsRoute: SessionSessionIdDetailsRoute,
}

const SessionSessionIdRouteWithChildren =
  SessionSessionIdRoute._addFileChildren(SessionSessionIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionSessionIdRoute: SessionSessionIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
