/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionSessionIdDetailsRouteImport } from './routes/session.$sessionId.details'
import { Route as SessionSessionIdActiveRouteImport } from './routes/session.$sessionId.active'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdDetailsRoute = SessionSessionIdDetailsRouteImport.update({
  id: '/session/$sessionId/details',
  path: '/session/$sessionId/details',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdActiveRoute = SessionSessionIdActiveRouteImport.update({
  id: '/session/$sessionId/active',
  path: '/session/$sessionId/active',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/session/$sessionId/active': typeof SessionSessionIdActiveRoute
  '/session/$sessionId/details': typeof SessionSessionIdDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/session/$sessionId/active': typeof SessionSessionIdActiveRoute
  '/session/$sessionId/details': typeof SessionSessionIdDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/session/$sessionId/active': typeof SessionSessionIdActiveRoute
  '/session/$sessionId/details': typeof SessionSessionIdDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/session/$sessionId/active' | '/session/$sessionId/details'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/session/$sessionId/active' | '/session/$sessionId/details'
  id:
    | '__root__'
    | '/'
    | '/session/$sessionId/active'
    | '/session/$sessionId/details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionSessionIdActiveRoute: typeof SessionSessionIdActiveRoute
  SessionSessionIdDetailsRoute: typeof SessionSessionIdDetailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId/details': {
      id: '/session/$sessionId/details'
      path: '/session/$sessionId/details'
      fullPath: '/session/$sessionId/details'
      preLoaderRoute: typeof SessionSessionIdDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId/active': {
      id: '/session/$sessionId/active'
      path: '/session/$sessionId/active'
      fullPath: '/session/$sessionId/active'
      preLoaderRoute: typeof SessionSessionIdActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionSessionIdActiveRoute: SessionSessionIdActiveRoute,
  SessionSessionIdDetailsRoute: SessionSessionIdDetailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
